backend:
  name: github
  repo: billys-animals/code.okanemochi.tk
  branch: master

# publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "img"

collections:
 - name: "posts"
   label: "Posts"
   folder: "content/posts"
   create: true
   slug: "{{slug}}"
   fields:
   - {label: "Title", name: "title", widget: "string"}
   - {label: "Category", name: "categories", widget: "list", required: false}
   - {label: "Tags", name: "tags", widget: "list", required: false}
   - {label: "Publish Date", name: "date", widget: "datetime"}
   - {label: "Draft", name: "draft", widget: "boolean", default: false}
   - {label: "Body", name: "body", widget: "markdown"}
